// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAan4K2bnWLKfXiMGICvsqRLx9rezKTMQQ',
    appId: '1:651131976291:web:60010ada0e92669b49d656',
    messagingSenderId: '651131976291',
    projectId: 'senhorita-5c5fd',
    authDomain: 'senhorita-5c5fd.firebaseapp.com',
    storageBucket: 'senhorita-5c5fd.firebasestorage.app',
    measurementId: 'G-QHY71V7ZQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCreW_LVCBNlOXeyHeyHu4Z20gF18nh4Nc',
    appId: '1:651131976291:android:b8e7176d3fb1b41749d656',
    messagingSenderId: '651131976291',
    projectId: 'senhorita-5c5fd',
    storageBucket: 'senhorita-5c5fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCocOT_FBJQDmIIe6GoFJrVHn5Z7RF8QFo',
    appId: '1:651131976291:ios:42c76077ea3fd6a449d656',
    messagingSenderId: '651131976291',
    projectId: 'senhorita-5c5fd',
    storageBucket: 'senhorita-5c5fd.firebasestorage.app',
    iosBundleId: 'com.example.senhorita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCocOT_FBJQDmIIe6GoFJrVHn5Z7RF8QFo',
    appId: '1:651131976291:ios:42c76077ea3fd6a449d656',
    messagingSenderId: '651131976291',
    projectId: 'senhorita-5c5fd',
    storageBucket: 'senhorita-5c5fd.firebasestorage.app',
    iosBundleId: 'com.example.senhorita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAan4K2bnWLKfXiMGICvsqRLx9rezKTMQQ',
    appId: '1:651131976291:web:be53b00e5ed2a9de49d656',
    messagingSenderId: '651131976291',
    projectId: 'senhorita-5c5fd',
    authDomain: 'senhorita-5c5fd.firebaseapp.com',
    storageBucket: 'senhorita-5c5fd.firebasestorage.app',
    measurementId: 'G-7ZJMZBQHT4',
  );
}
